Fix adding PURE to functions
If a statement group has owner=caller a capsule argument will be added
which is intent(OUT). This capsule is used to release memory by the
user.

gfortran 13
  481 |         pure function c_class1_get_path(self, SHT_rv_capsule) &
      |                                                            1
Error: Argument ‘sht_rv_capsule’ of pure function ‘c_class1_get_path’ at (1)
must be INTENT(IN) or VALUE

intel 2025
 error #7115: The specification-part of a PURE function must specify that all dummy arguments have explicitly declared INTENT(IN) except procedure arguments and arguments with the POINTER or VALUE attributes.   [SHT_RV_CAPSULE]
        pure function c_class1_get_path(self, SHT_rv_capsule) &
----------------------------------------------^