Remove shared_ptr as subclass
Change derived types object_shared and object_weak to remove EXTENDS.
This helps the assignment overload which could not distinguish
Object=Object from std::shared_ptr<Object>=Object

Add support for std::shared_ptr<Object>=Object with
c_mixin_operator_assignment_fmtdict_makeshared which creates a new
std::shared_ptr then resets to use Object pointer.
This avoids the error:
  111 |       sp1 = object()
      |            1
Error: Cannot convert TYPE(object) to TYPE(object_shared) at (1)

Add ClassNode.shared_baseclass to help with statements -
baseclass.cxx_type.  It emulates the old inheritance behavior. Should
be replaced with targs[0].cxx_type since std::shared_ptr is templated.