Revert to 3.9 for github
3.10 introduced the message:
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

Needs some investigating before defining PY_SSIZE_T_CLEAN.