Test passing function and subroutine to same function
gfortran 12.1 assumes that since callback2_external was passed a
subroutine, it must always be passed a subroutine and reports:
     Error: Interface mismatch in dummy procedure ‘incr’ at (1):
     'incr2_fun' is not a subroutine