Support +allocatable(nvar) for Python wrapper
Rename statement py_native_out_allocatable_numpy by adding a mold to
the end when used with +alloctable(mold=var). This calls
PyArray_NewLikeArray. Otherwise, alias to py_native_out_dimension_numpy
which calls PyArray_SimpleNewFromData.

Split fmt.npy_intp into npy_intp_decl and npy_intp_asgn to avoid
compiler error:
  error: jump to label 'fail' [-fpermissive]
  error:   crosses initialization of 'npy_intp SHD_arg2 [1]

With +allocatable(nvar) npy_intp_asgn must be after
PyArg_ParseTupleAndKeywords since nvars is assigned by that routine.