Add C_prefix to derived type names
If multiple Shroud wrapped modules are used in a file, they will conflict.
Ideally some of the types would be PRIVATE.
However, gfortran does not allow PRIVATE and BIND(C) to be mixed since it
sees them as contradictory.
Error: Derived type 'shroud_capsule_data' at (1) cannot be declared with both PRIVATE and BIND(C) attributes
Instead, mangle the type name with C_prefix to make them unique.