Fixes for test-fortran-strings-cfi
Always use len=: for allocatable and pointer character arguments.
Required for CFI. Remove fmt.f_char_len.
gfortran:
  Error: Allocatable character dummy argument ‘strs’ at (1)
  must have deferred length as procedure ‘fetch_array_string_alloc_len’
  is BIND(C)
intel:
  error #8532: A character dummy argument with length other than
  1 is not interoperable.

metaattrs.py - do not assume 'char**' is a +rank(1).
The test is returning a pointer to a string, not an array.